// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductionCFD2.Data;

#nullable disable

namespace ProductionCFD2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductionCFD2.Models.Material", b =>
                {
                    b.Property<int>("Material_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Material_Id"));

                    b.Property<string>("Material_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Material_Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("ProductionCFD2.Models.ProductionTable", b =>
                {
                    b.Property<int>("Production_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Production_Id"));

                    b.Property<int>("EndCut")
                        .HasColumnType("int");

                    b.Property<decimal>("Finish_Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Grinding_Loss")
                        .HasColumnType("int");

                    b.Property<int>("Grinding_Wheel")
                        .HasColumnType("int");

                    b.Property<string>("Input_Batch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Material_Id")
                        .HasColumnType("int");

                    b.Property<string>("Material_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Production_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rolling_Plan_Size")
                        .HasColumnType("int");

                    b.Property<int>("Sample_Loss")
                        .HasColumnType("int");

                    b.Property<int>("ShiftIncharge_Id")
                        .HasColumnType("int");

                    b.Property<int>("Shift_Id")
                        .HasColumnType("int");

                    b.Property<int>("Total_Input")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Yield")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Production_Id");

                    b.HasIndex("Material_Id");

                    b.HasIndex("ShiftIncharge_Id");

                    b.HasIndex("Shift_Id");

                    b.ToTable("ProductionTables");
                });

            modelBuilder.Entity("ProductionCFD2.Models.Shift", b =>
                {
                    b.Property<int>("Shift_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Shift_Id"));

                    b.Property<string>("Shift_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shift_Id");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("ProductionCFD2.Models.ShiftIncharge", b =>
                {
                    b.Property<int>("ShiftIncharge_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftIncharge_Id"));

                    b.Property<string>("ShiftIncharge_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShiftIncharge_Id");

                    b.ToTable("ShiftIncharges");
                });

            modelBuilder.Entity("ProductionCFD2.Models.ProductionTable", b =>
                {
                    b.HasOne("ProductionCFD2.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("Material_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionCFD2.Models.ShiftIncharge", "ShiftIncharge")
                        .WithMany()
                        .HasForeignKey("ShiftIncharge_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionCFD2.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("Shift_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Shift");

                    b.Navigation("ShiftIncharge");
                });
#pragma warning restore 612, 618
        }
    }
}
